site_name: Pitch Dark
site_description: Dark Minimal Theme for Bootstrap

copyright: copyright &copy; Lucas Ramage. All Rights Reserved.

remote_branch: gh-pages

theme: pitch-dark

nav:
  - Home: index.md
  - About: about.md
  - Sample Post: posts/sample-post.md
  - Contact: contact.md

extra:
  color: '#060606'
  social:
    github: https://github.com


plugins: []
